name: Run my python

on:
  push: # do this evey time

job:
  build:
  name: set up environment
  run-on: ubuntu-lastest
  steps:
  - uses: action/checkout@v2
  - name: Run my python
    run: |
      python3 test1.py
